apiVersion: apps/v1
kind: Deployment
metadata:
 name: "devapp"
 labels:
   app: "devapp"
spec:
 replicas: 1
 selector:
   matchLabels:
     app: "devapp"
 template:
   metadata:
     labels:
       app: "devapp"
   spec:
     containers:
     - name: devapp
       image: "wil42/playground:v2"
       ports:
       - containerPort: 8888

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "devapp"
spec:
  rules:
    - http:
      host: devapp
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "devapp"
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: "devapp"
spec:
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
  selector:
    app: 'devapp'